### ISSUE TITLE
Maximum call stack size exceeeded

### ISSUE THREAD

**Issue by thitemple** [rtfeldman/node-test-runner#290]
I'm converting an app to Elm 0.19 and I was updating my tests, I was just following any compiling issues I had and at some point I fixed them (at least I think so) and now I'm seeing the following error: 

I'm using beta9 on a Win10 computer

![image](https://user-images.githubusercontent.com/368734/45647761-b2a6c480-ba94-11e8-9833-5a5423db2919.png)

I'm not sure how can I get more information to help with this issue, or if you have something else I can do to try it.

I'm not even sure if this is an `elm-test` issue or `elm-explorations\test` issue

Thanks

**Comment by thitemple** [comment]
Just to add some more information, I removed all my test files and add a test file a time to find what was causing the issue.

I had a test for a decoder that was failing because I forgot to update it and that was causing the issue. When I fixed the test everything went back to normal, but I don't understand why it was yielding this error.

**Comment by mgold** [comment]
Can you isolate the issue? Give us the smallest test (and app code) that causes the issue?

**Comment by rtfeldman** [comment]
Unfortunately https://github.com/rtfeldman/node-test-runner/pull/319 didn't fix this. I can still reproduce it on `master` with any failing fuzz test. (Non fuzz tests seem to be fine though.)
